# Generated by Django 5.0.14 on 2026-05-26 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('average_rating', models.FloatField(default=0.0)),
                ('is_trending', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stalls.product')),
            ],
        ),
        migrations.CreateModel(
            name='Stall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stall_logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='stall_banners/')),
                ('cuisine_type', models.CharField(help_text='e.g. Grill, Seafood, Filipino, Desserts', max_length=100)),
                ('price_range', models.CharField(choices=[('$', 'Budget ($)'), ('$$', 'Moderate ($$)'), ('$$$', 'Premium ($$$)')], default='$$', max_length=5)),
                ('operating_hours', models.JSONField(blank=True, default=dict, help_text="e.g. {'Monday': '4PM-11PM'}")),
                ('average_rating', models.FloatField(default=0.0)),
                ('reviews_count', models.IntegerField(default=0)),
                ('crowd_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stall', to='authentication.sellerprofile')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='stall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='stalls.stall'),
        ),
        migrations.CreateModel(
            name='StallLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(default=13.937)),
                ('longitude', models.FloatField(default=121.613)),
                ('section_name', models.CharField(help_text='e.g., Row A, Space 3', max_length=100)),
                ('description', models.CharField(blank=True, help_text='e.g., Near the main stage entrance', max_length=255)),
                ('stall', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='stalls.stall')),
            ],
        ),
    ]
