# Generated by Django 6.0.5 on 2026-05-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stalls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StallImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='stall_images/')),
            ],
        ),
        migrations.AddField(
            model_name='stall',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='stalls', to='stalls.stallimage'),
        ),
    ]
