# Generated by Django 5.0.14 on 2026-05-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('STALL_VIEW', 'Stall View'), ('PRODUCT_VIEW', 'Product View'), ('QR_SCAN', 'QR Code Scan'), ('SEARCH_QUERY', 'Search Query'), ('CROWD_REPORT', 'Crowd Level Report')], max_length=20)),
                ('target_id', models.IntegerField(blank=True, help_text='ID of target Stall/Product', null=True)),
                ('target_name', models.CharField(blank=True, help_text='Meta query term or name', max_length=255)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-calculated_at', '-score'],
            },
        ),
    ]
